
# from DA_surveyinfo_for_polyfun.R (local script) LOAD LIBRARIES
require(tidyverse)
library(dplyr)
setwd("~/Documents/Dog-group/2020/Autism_Border_Collie/Morrill_data/DA_cf4_analyses/DA_rerun_2024-10-11/DA_surveyinfo_for_polyfun_controlGWASheight/")

famQC5 <- read.csv("~/Documents/Dog-group/2020/Autism_Border_Collie/Morrill_data/DA_cf4_analyses/DA_rerun_2024-10-11/DA_MERGED_GENCOVE_AXIOM_QC5.fam", 
                   sep= " ", header=F, col.names =c("FID","IID","F","M","sex","phe"))
head(famQC5) 
nrow(famQC5)
tail(famQC5)
famQC5$IID <- as.character(famQC5$IID)

####load covar file incl. q121 - generated by Vista Feb 8th 2024####
updated_covar <- read.csv("~/Documents/Dog-group/2020/Autism_Border_Collie/Morrill_data/DA_cf4_analyses/DarwinsDogs_Q121_height_age_sex_batch_GENCOVE_AXIOM_QC4.tsv", sep= "\t", header=T)
head(updated_covar) 
nrow(updated_covar)
updated_covar$IID <- as.character(updated_covar$dog)

data1 <- left_join(famQC5, updated_covar, by="IID")
head(data1)
table(data1$sex_numeric, exclude=NULL)

#write.table(data1, file= "q121_age_sex_DA_MERGED_GENCOVE_AXIOM_QC5.fam", row.names =F, sep = "\t", col.names= T, quote = F )

data1 <- read.csv("q121_age_sex_DA_MERGED_GENCOVE_AXIOM_QC5.fam", sep= "\t", header=T)

####1. SIZE####
SIZE <- read.table("Q121A.pheno", header= F, col.names = c("FID", "IID", "pheno"),   sep= " ")
SIZE$IID <- as.character(SIZE$IID)
table(SIZE$pheno, exclude=NULL)

SIZE2 <- left_join(data1, SIZE, by="IID")
nrow(SIZE2)
# Set pheno to NA where sex_numeric is NA
SIZE2$pheno[is.na(SIZE2$sex_numeric)] <- NA

# Recode sex_numeric: 1=1, 2=0, NA=NA
SIZE2$sex_numeric <- ifelse(SIZE2$sex_numeric == 1, 1, ifelse(SIZE2$sex_numeric == 2, 0, NA))

# Recode pheno NA to -9
SIZE2$pheno[is.na(SIZE2$pheno)] <- -9

# Display the table after modification
table(SIZE2$sex_numeric, SIZE2$pheno, exclude=NULL)

SIZE_fam <- data.frame(FID= SIZE2$IID, IID = SIZE2$IID, F=SIZE2$M, M=SIZE2$M, sex=SIZE2$sex_numeric, phe=SIZE2$pheno) 
#write.table(SIZE_fam, file= "SIZE_DA_MERGED_GENCOVE_AXIOM_QC5.fam", row.names =F, sep = "\t", col.names= F, quote = F )





###########################################################
#(11) STUCK. Quantitative.Stuck behind objects. Q36A.pheno
####11. STUCK ####
STUCK <- read.table("Q36A.pheno", header= F, col.names = c("FID", "IID", "pheno"),   sep= " ")
STUCK$IID <- as.character(STUCK$IID)
head(STUCK)
nrow(STUCK)
table(STUCK$pheno, exclude=NULL)

nrow(data1)
STUCK2 <- left_join(data1, STUCK, by="IID", keep =FALSE)
nrow(STUCK2)
table(STUCK2$sex_numeric, STUCK2$pheno, exclude=NULL)

# Set pheno to NA where sex_numeric is NA
STUCK2$pheno[is.na(STUCK2$sex_numeric)] <- NA

# Recode sex_numeric: 1=1, 2=0, NA=NA
STUCK2$sex_numeric <- ifelse(STUCK2$sex_numeric == 1, 1, ifelse(STUCK2$sex_numeric == 2, 0, NA))

# Recode pheno NA to -9
STUCK2$pheno[is.na(STUCK2$pheno)] <- -9

# Display the table after modification
table(STUCK2$sex_numeric, STUCK2$pheno, exclude=NULL)
table(STUCK2$pheno, exclude=NULL)

STUCK_fam <- data.frame(FID= STUCK2$IID, IID = STUCK2$IID, F=STUCK2$M, M=STUCK2$M, sex=STUCK2$sex_numeric, phe=STUCK2$pheno) 
head(STUCK_fam)
nrow(STUCK_fam)

write.table(STUCK_fam, file= "STUCK_DA_MERGED_GENCOVE_AXIOM_QC5.fam", row.names =F, sep = "\t", col.names= F, quote = F )

